const DNATURE_WHATSAPP_PHONE = '50671848868';
const DNATURE_WHATSAPP_DISPLAY = '+506 7184-8868';
const DNATURE_SUPPORT_HOURS = 'Lunes a viernes, de 8:00 a. m. a 5:00 p. m.';
const DNATURE_SUPPORT_RESPONSE = 'Respondemos dentro de 2 horas hábiles.';

export {
  DNATURE_SUPPORT_HOURS,
  DNATURE_SUPPORT_RESPONSE,
  DNATURE_WHATSAPP_DISPLAY,
  DNATURE_WHATSAPP_PHONE,
};
